
let APP_CONSTANTS = {
    API_SLOW_DOWN_CONFIG: {
        SIMULTANEOUS_REQUEST_COUNT: 15 * 60 * 1000,
        DELAY_AFTER: 100,
        DELAY_IN_MILLISECONDS: 500
    },
    JWT_CONFIG: {
        TOKEN_EXPIRATION_IN_SECONDS: 36000
    },
    MONGODB_CONFIG: {
        LOCAL_DB_CONNECTION_URL: 'mongodb://localhost:27017/cookfrenzy',
        SERVER_SELECTION_TIMEOUT_IN_MILLISECONDS: 5000,
        SERVER_CONNECTION_RETRY_IN_SECONDS: 5
    },
    HTTP_STATUS_CODES: {
        HTTP_OK: 200,
        HTTP_CREATED: 201,
        HTTP_BAD_REQUEST: 400,
        HTTP_UNAUTHORIZED: 401,
        HTTP_FORBIDDEN: 403,
        HTTP_NOT_FOUND: 404,
        HTTP_UNPROCESSABLE_ENTITY: 422,
        HTTP_INTERNAL_SERVER_ERROR: 500
    },
    ORDER: {
        SHIPPING_COST: 400
    }
}

export const APP_CONST = APP_CONSTANTS;
